apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-test-
spec:
    entrypoint: workflow-test
    arguments:
      parameters:
      - name: param_hostname
        value: ''
      - name: param_filter_type
        value: 'select_equal'
      - name: param_min_x
        value: '-113107.81'
      - name: param_max_y
        value: '726783.87'
      - name: param_min_y
        value: '214783.87'
      - name: param_attribute
        value: 'raw_classification'
      - name: param_login
        value: ''
      - name: param_apply_filter_value
        value: '1'
      - name: param_n_tiles_side
        value: '512'
      - name: param_password
        value: ''
      - name: param_max_x
        value: '398892.19'
      - name: param_validate_precision
        value: '0.000001'
      - name: param_feature_name
        value: 'perc_95_normalized_height'
      - name: param_tile_mesh_size
        value: '10.'
    templates:
    - name: workflow-test
      dag:
        tasks:
        - name: fetch-laz-files-08-04-22
          template: fetch-laz-files-08-04-22-tmp
          arguments:
            parameters:
            - {name: param_login, value: "{{workflow.parameters.param_login}}"}
            - {name: param_hostname, value: "{{workflow.parameters.param_hostname}}"}
            - {name: param_password, value: "{{workflow.parameters.param_password}}"}
        - name: retiling-08-04-22
          dependencies: [ fetch-laz-files-08-04-22 ]
          template: retiling-08-04-22-tmp
          arguments:
            parameters:
            - {name: laz_files, value: "{{item}}"}
            - {name: param_login, value: "{{workflow.parameters.param_login}}"}
            - {name: param_max_y, value: "{{workflow.parameters.param_max_y}}"}
            - {name: param_hostname, value: "{{workflow.parameters.param_hostname}}"}
            - {name: param_min_y, value: "{{workflow.parameters.param_min_y}}"}
            - {name: param_min_x, value: "{{workflow.parameters.param_min_x}}"}
            - {name: param_n_tiles_side, value: "{{workflow.parameters.param_n_tiles_side}}"}
            - {name: param_max_x, value: "{{workflow.parameters.param_max_x}}"}
            - {name: param_password, value: "{{workflow.parameters.param_password}}"}
          withParam: "{{tasks.fetch-laz-files-08-04-22.outputs.parameters.outs}}"
        - name: fetch-tiles-08-04-22
          dependencies: [ retiling-08-04-22 ]
          template: fetch-tiles-08-04-22-tmp
          arguments:
            parameters:
            - {name: remote_path_retiled, value: "{{tasks.retiling-08-04-22.outputs.parameters.outs}}"}
            - {name: param_login, value: "{{workflow.parameters.param_login}}"}
            - {name: param_hostname, value: "{{workflow.parameters.param_hostname}}"}
            - {name: param_password, value: "{{workflow.parameters.param_password}}"}
        - name: feature-extraction-08-04-22
          dependencies: [ fetch-tiles-08-04-22 ]
          template: feature-extraction-08-04-22-tmp
          arguments:
            parameters:
            - {name: tiles, value: "{{item}}"}
            - {name: param_login, value: "{{workflow.parameters.param_login}}"}
            - {name: param_validate_precision, value: "{{workflow.parameters.param_validate_precision}}"}
            - {name: param_max_y, value: "{{workflow.parameters.param_max_y}}"}
            - {name: param_filter_type, value: "{{workflow.parameters.param_filter_type}}"}
            - {name: param_hostname, value: "{{workflow.parameters.param_hostname}}"}
            - {name: param_tile_mesh_size, value: "{{workflow.parameters.param_tile_mesh_size}}"}
            - {name: param_min_x, value: "{{workflow.parameters.param_min_x}}"}
            - {name: param_min_y, value: "{{workflow.parameters.param_min_y}}"}
            - {name: param_n_tiles_side, value: "{{workflow.parameters.param_n_tiles_side}}"}
            - {name: param_max_x, value: "{{workflow.parameters.param_max_x}}"}
            - {name: param_apply_filter_value, value: "{{workflow.parameters.param_apply_filter_value}}"}
            - {name: param_password, value: "{{workflow.parameters.param_password}}"}
            - {name: param_feature_name, value: "{{workflow.parameters.param_feature_name}}"}
            - {name: param_attribute, value: "{{workflow.parameters.param_attribute}}"}
          withParam: "{{tasks.fetch-tiles-08-04-22.outputs.parameters.outs}}"
        - name: geotiff-export-08-04-22
          dependencies: [ feature-extraction-08-04-22 ]
          template: geotiff-export-08-04-22-tmp
          arguments:
            parameters:
            - {name: features, value: "{{tasks.feature-extraction-08-04-22.outputs.parameters.outs}}"}
            - {name: param_login, value: "{{workflow.parameters.param_login}}"}
            - {name: param_hostname, value: "{{workflow.parameters.param_hostname}}"}
            - {name: param_password, value: "{{workflow.parameters.param_password}}"}
            - {name: param_feature_name, value: "{{workflow.parameters.param_feature_name}}"}

    - name: fetch-laz-files-08-04-22-tmp
      outputs:
        parameters:
          - name: outs
            valueFrom:
              path: /tmp/outputs.json
      container:
        image: "qcdis/fetch-laz-files-08-04-22"
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate;
            python fetch-laz-files-08-04-22.py
            --param_login {{workflow.parameters.param_login}}
            --param_hostname {{workflow.parameters.param_hostname}}
            --param_password {{workflow.parameters.param_password}};
    - name: retiling-08-04-22-tmp
      inputs:
        parameters:
        - name: laz_files
        - name: param_login
        - name: param_max_y
        - name: param_hostname
        - name: param_min_y
        - name: param_min_x
        - name: param_n_tiles_side
        - name: param_max_x
        - name: param_password
      outputs:
        parameters:
          - name: outs
            valueFrom:
              path: /tmp/outputs.json
      container:
        image: "qcdis/retiling-08-04-22"
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate;
            echo  {{inputs.parameters.laz_files}} > /tmp/inputs.json;
            python retiling-08-04-22.py
            --param_login {{workflow.parameters.param_login}}
            --param_max_y {{workflow.parameters.param_max_y}}
            --param_hostname {{workflow.parameters.param_hostname}}
            --param_min_y {{workflow.parameters.param_min_y}}
            --param_min_x {{workflow.parameters.param_min_x}}
            --param_n_tiles_side {{workflow.parameters.param_n_tiles_side}}
            --param_max_x {{workflow.parameters.param_max_x}}
            --param_password {{workflow.parameters.param_password}};
    - name: fetch-tiles-08-04-22-tmp
      inputs:
        parameters:
        - name: remote_path_retiled
        - name: param_login
        - name: param_hostname
        - name: param_password
      outputs:
        parameters:
          - name: outs
            valueFrom:
              path: /tmp/outputs.json
      container:
        image: "qcdis/fetch-tiles-08-04-22"
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate;
            echo  {{inputs.parameters.remote_path_retiled}} > /tmp/inputs.json;
            python fetch-tiles-08-04-22.py
            --param_login {{workflow.parameters.param_login}}
            --param_hostname {{workflow.parameters.param_hostname}}
            --param_password {{workflow.parameters.param_password}};
    - name: feature-extraction-08-04-22-tmp
      inputs:
        parameters:
        - name: tiles
        - name: param_login
        - name: param_validate_precision
        - name: param_max_y
        - name: param_filter_type
        - name: param_hostname
        - name: param_tile_mesh_size
        - name: param_min_x
        - name: param_min_y
        - name: param_n_tiles_side
        - name: param_max_x
        - name: param_apply_filter_value
        - name: param_password
        - name: param_feature_name
        - name: param_attribute
      outputs:
        parameters:
          - name: outs
            valueFrom:
              path: /tmp/outputs.json
      container:
        image: "qcdis/feature-extraction-08-04-22"
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate;
            echo  {{inputs.parameters.tiles}} > /tmp/inputs.json;
            python feature-extraction-08-04-22.py
            --param_login {{workflow.parameters.param_login}}
            --param_validate_precision {{workflow.parameters.param_validate_precision}}
            --param_max_y {{workflow.parameters.param_max_y}}
            --param_filter_type {{workflow.parameters.param_filter_type}}
            --param_hostname {{workflow.parameters.param_hostname}}
            --param_tile_mesh_size {{workflow.parameters.param_tile_mesh_size}}
            --param_min_x {{workflow.parameters.param_min_x}}
            --param_min_y {{workflow.parameters.param_min_y}}
            --param_n_tiles_side {{workflow.parameters.param_n_tiles_side}}
            --param_max_x {{workflow.parameters.param_max_x}}
            --param_apply_filter_value {{workflow.parameters.param_apply_filter_value}}
            --param_password {{workflow.parameters.param_password}}
            --param_feature_name {{workflow.parameters.param_feature_name}}
            --param_attribute {{workflow.parameters.param_attribute}};
    - name: geotiff-export-08-04-22-tmp
      inputs:
        parameters:
        - name: features
        - name: param_login
        - name: param_hostname
        - name: param_password
        - name: param_feature_name
      outputs:
        parameters:
          - name: outs
            valueFrom:
              path: /tmp/outputs.json
      container:
        image: "qcdis/geotiff-export-08-04-22"
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate;
            echo  {{inputs.parameters.features}} > /tmp/inputs.json;
            python geotiff-export-08-04-22.py
            --param_login {{workflow.parameters.param_login}}
            --param_hostname {{workflow.parameters.param_hostname}}
            --param_password {{workflow.parameters.param_password}}
            --param_feature_name {{workflow.parameters.param_feature_name}};
