apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: n-a-a-vre-user-
  labels:
    vlab_slug: n-a-a-vre
spec:
    entrypoint: n-a-a-vre-user
    serviceAccountName: executor
    volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: [ "ReadWriteMany" ]
        persistentVolumeReclaimPolicy: Delete
        resources:
          requests:
            storage: 1Gi
    arguments:
      parameters:
    templates:
    - name: n-a-a-vre-user
      dag:
        tasks:
        - name: download-sample-tif-dev-user-name-domain-com-e33e620
          template: download-sample-tif-dev-user-name-domain-com-e33e620-tmp
        - name: visualize-rasterio-sample-tif-dev-user-name-domain-com-80091fe
          dependencies: [ download-sample-tif-dev-user-name-domain-com-e33e620 ]
          template: visualize-rasterio-sample-tif-dev-user-name-domain-com-80091fe-tmp
          arguments:
            parameters:
            - {name: filename_118cef6, value: "{{tasks.download-sample-tif-dev-user-name-domain-com-e33e620.outputs.parameters.filename_118cef6}}"}
    - name: download-sample-tif-dev-user-name-domain-com-e33e620-tmp
      outputs:
        parameters:
          - name: filename_118cef6
            valueFrom:
              path: /tmp/filename_118cef6.json
      container:
        image: "ghcr.io/qcdis/naavre-cells-test-3/download-sample-tif-dev-user-name-domain-com:1606924"
        imagePullPolicy: Always
        volumeMounts:
        - name: workdir
          mountPath: /tmp/data
        env:
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate; python /app/task.py
            --id  118cef6;
    - name: visualize-rasterio-sample-tif-dev-user-name-domain-com-80091fe-tmp
      inputs:
        parameters:
        - name: filename_118cef6
      outputs:
        parameters:
      container:
        image: "ghcr.io/qcdis/naavre-cells-test-3/visualize-rasterio-sample-tif-dev-user-name-domain-com:4734ef2"
        imagePullPolicy: Always
        volumeMounts:
        - name: workdir
          mountPath: /tmp/data
        env:
        command: ["/bin/bash", "-c"]
        args:
          - source /venv/bin/activate; ipython kernel install --user; python /app/task.py
            --filename '{{inputs.parameters.filename_118cef6}}'
            --id  a109edd;
            jupyter execute /app/task-output.ipynb --allow-errors;
            jupyter nbconvert --no-input --execute /app/task-output.ipynb --to html;
            cp /app/task-output.html /tmp/data/visualize-rasterio-sample-tif-dev-user-name-domain-com-80091fe-output.html;
            jupyter notebook --port 5173 --NotebookApp.ip='0.0.0.0' --NotebookApp.allow_origin='*' --NotebookApp.base_url=/naavre-visualizer-notebook
      metadata:
        labels:
          app: naavre-visualizer-notebook
